---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8070
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: first
server:
  port: 8071
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8072/eureka/,http://localhost:8073/eureka/

---
spring:
  profiles: second
server:
  port: 8072
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8073/eureka/,http://localhost:8071/eureka/

---
spring:
  profiles: third
server:
  port: 8073
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/,http://localhost:8072/eureka/
