eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/,http://localhost:8071/eureka/,http://localhost:8072/eureka/,http://localhost:8073/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
